### ISSUE TITLE
Synthetic datasets

### ISSUE THREAD

**Issue by liu-jc** [SwiftieH/IGNN#1]
Dear authors,

Thanks for your impressive work. I have a few questions about the synthetic datasets. 
1) In Figure 1, the x-axis starts with 0. Does it mean that the length is 0? How can we create chains without nodes? I think it would be totally a none graph?  
2) You mentioned in the paper that 20 nodes for training. But the number of nodes is not fixed for datasets with chains having different lengths, right? So, the setting 20/100/200 for train/val/test is only for the dataset with 20 chains for each class and 10-length chains? Because the number of nodes is decided by `c*n*l` as you stated in the [code](https://github.com/SwiftieH/IGNN/blob/5d4fd69951c10cda452773ac92f98440ffebd453/nodeclassification/utils.py#L109). 

Thanks in advance.

**Comment by beeperman** [comment]
1. A chain of length 0 is a single node with no connection to other nodes. That is, we are asking the model to predict results solely based on the feature (where the info is provided). This is the trivial case without graph-structured info.
2. The graph is constructed as a single huge graph (c*n*l = 400, c=2, n=20, l=10) although we know that each chain is separated from each other. At training and testing time, we sample 20/100/200 nodes from the graph (without replacement). At length <10, we made n larger so that such sampling is possible. As far as I remember, we used the same 20/100/200 setting across the board.

I hope this answers the questions.
