### ISSUE TITLE
 The result Different from paper（与论文不符）

### ISSUE THREAD

**Issue by WhateverSir** [SwiftieH/IGNN#3]
I run this code. My f1-micro of **PPI** is 0.491,while in paper it is 0.976. And during the process, the following appears many times:
Iterations not converging! tensor(32., device='cuda:0') max itrs .
Waiting for you answer!

**Comment by steven-hh-ding** [comment]
same here. any reply? cannot reproduce with the same code posted.

**Comment by steven-hh-ding** [comment]
@SwiftieH

**Comment by SwiftieH** [comment]
Hi there,

Sorry for this late reply. 
We tested `train_IGNN_PPI.py` again and the result is  `0.9755884742294925 at epoch 931`, which is consistent with our paper. I attached the training output log here as well as our conda environment. I hope this can be helpful for your reproduction.

In terms of the warning, it is normal to still have the error in equilibrium equation be non-zero due to numerical reasons as long as that number does not explode. If that number gets too big, the picard iteration does not converge. And you will see significant performance degradation. This might result from too large kappa.
[PPI_output_log.txt](https://github.com/SwiftieH/IGNN/files/7052441/PPI_output_log.txt)
[package_info.txt](https://github.com/SwiftieH/IGNN/files/7052442/package_info.txt)

Please let us know if you have any further questions.

**Comment by steven-hh-ding** [comment]
thank you!
